- name: Ensure Image Builder packages are installed.
  package:
    name: "{{ __ib_packages[ib_packages]
              if ib_packages in __ib_package_types
              else ib_packages }}"
    state: present

# for future use when lorax-composer is deprecated and dropped.
- name: Remove undesired Image Builder packages
  package:
    name: "{{ __ib_packages_exclude }}"
    state: absent
  when: __ib_packages_exclude is defined
