---
__ib_daemon: osbuild-composer

__ib_packages_minimal:
  - composer-cli
  - "{{ __ib_daemon }}"

__ib_packages_default:
  - cockpit-composer

__ib_packages_full:
  - cockpit-composer

__ib_packages:
  minimal: "{{ __ib_packages_minimal }}"
  default: "{{ __ib_packages_minimal + __ib_packages_default }}"
  full: "{{ __ib_packages_minimal + __ib_packages_default + __ib_packages_full }}"

